### ISSUE TITLE
0.1 Regression Tests

### ISSUE THREAD

**Issue by dwbolt** [ETPRI/Graph#23]
widgetNode  - escaping ' / " etc.
widgetTableQuerry
widgetTableRelations
app

checking that db is empty.

**Comment by dwbolt** [comment]
- [ ] L1

- [ ] L2

- [ ] L3

- [ ] L4

- [ ] L5

**Comment by AmyFiori** [comment]
When you assign an issue to me, it would be really helpful if you could add a description of what you want done. "card / issue of LV1 test" isn't a lot to go on. I THINK I've finished this because I redid the regression testing files.
