### ISSUE TITLE
0.1 ordered relation versions

### ISSUE THREAD

**Issue by dwbolt** [ETPRI/Graph#25]
each person logged on can order relations in a difference order

store order in viewOrder relation attribute from person to node

**Comment by AmyFiori** [comment]
We'll need a login system already working before we can start on this - would you like me to start designing one?

**Comment by dwbolt** [comment]
:2018-03-01:  version works, by creating a view link from node to logged in person and storing order in attribute of logged in person

talk about next version,  have each person own a view, they create their own links and order, a voting (consists view shows result) a person can view the links of other and add them their list, a copy is made.  A person can (delete links they created) they can not delete copies made of their links)

**Comment by dwbolt** [comment]
:2018-03-06: each person has there own view and own order of relations.
