### ISSUE TITLE
staff alpha

### ISSUE THREAD

**Issue by dwbolt** [ETPRI/Graph#31]
:2018-02-14: ideas from meeting

voting system - 

1. #number items each person can submit
2. when is pass, fail, table
3. about of time

Status:
Goal
IDEAS
Steps -> planing
Tasks

vision - mission - values
project management - GIST -       Plan -> Do ->Check -> Adjust 
goals - project

plan exection

agenda - history

demo of:
bitrix24.com project management system - 
new York cares 
and others next meeting - 

policy -
#
capture minutines in system - 

look - at agenda documents - 

lists - things that are broken - All my lists

**Comment by MaryWoody** [comment]
Test comment 1
